export default {
  _id: {
    $oid: "5aee98ab5d8851d4b7d856b4"
  },
  ID: 13,
  Category: "Fish",
  CommonName: "Mosquitofish",
  AcademicalName: "Gambusia Holbrooki",
  BriefIntroduction:
    "Greenish olive to brown on the back, the sides are grey with a bluish sheen with a belly silvery-white. Females have a distinct black blotch surrounded by a golden patch occurring just above the vent. Males have a highly modified anal fin, the third, fourth and fifth rays of which are elongated and thickened to form a 'gonopodium' which is used to inseminate the female. Females are also larger than males with maximum standard lenghts of 60mm and 35mm respectively.",
  Distribution:
    "Range includes the Atlantic and Gulf slope drainages from southern New Jersey to the Pascagoula River and nearby streams, southeastern Mississippi; absent from the Mobile Bay drainage except the extreme southern part (Page and Burr 2011). This species has been introduced outside the native range; it may be established in some of these areas.",
  Habitat:
    "Gambusia holbrooki prefer warm, slow flowing or still waters, and occur amongst aquatic vegetation at the edge of waterbodies in water depths of 10cm or less (Merrick and Schmida 1984; McDowall 1996; Arthington et al. 1999). Although gambusia can tolerate a broad range of environmental conditions, they tend to avoid rapid discharge, naturally variable creeks and rivers and areas of dense surface vegetation, that can obstruct access for feeding on the surface (Meffe 1984; Arthington et al. 1990; Galat and Robinson, 1992).",
  PhysicalDescription:
    "Northern snakeheads have long slender bodies, and a flattened head with eyes that are located on the front of the head. The head has a large mouth with a protruding lower jaw. The fish also have very sharp teeth, located in their lower jaw. Northern snakeheads have dorsal and anal fins that are elongated and span nearly half of the ventral posterior portion of the body, or the bottom side of the fish\u2019s body located closer to the tail fin. Also, the fish has small pelvic fins that are located directly behind their pectoral fins that are located on either side of the snakeheads\u2019 head. The northern snakehead has approximately 8 rows of scales above, and 12 rows of scales below their lateral line. Northern snakeheads change color as they mature. As they are in their youth the most common color scheme is a golden brown to pale gray color. Once mature, northern snakeheads are typically a darker brown with dark brown-red blotches covering the entire body. Fully mature northern snakeheads range from 44 cm to 72 cm. However, in some locations northern snakeheads have been found to grow up to 150 cm and weigh nearly 8 kg. Females tend to be smaller than males, and have a shorter dorsal fin along with smaller snout and upper jaw./nIn North America, northern snakehead can be mistaken for native species, such as the bowfin (Amia calva) and burbot (Lota lota). American bowfin pelvic fins are located further back on the body, whereas the northern snakeheads\u2019 pelvic fins are located directly behind the pectoral fins. Also the bowfin has a divided dorsal fin, with the northern snakehead dorsal fin is a single long structure. The primary difference between northern snakehead and burbot is that the burbot has barbels similar to a catfish, also the burbot\u2019s anal fin is quite short compared to the long anal fin of a northern snakehead. (Courtenay and Williams, 2004; Lapointe, et al., 2013; Wang, et al., 2012)",
  FoodHabits:
    "The northern snakehead is a predatory fish species that feed mostly on other fish, frogs, freshwater crustaceans, and some insects. As juvenile fish, the northern snakehead commonly feeds on small crustaceans and other fish larvae. A study conducted by Dukravets and Machulin ([1978], as cited in Courtney and Williams, 2012) showed that the fish would feed on other fish up to 33% of their own body size. The northern snakehead becomes predominately carnivorous when they reach 4cm in length. Once fully mature, other fish make up to 90% of the northern snakeheads\u2019 diet. In their introduced range, specifically in the Potomac River system, northern snakeheads have been found to prey upon banded killifish (Fundulus diaphanous), white perch (Morone americana), pumpkinseed fish (Lepomis gibbosus), bluegill (Lepomis macrochirus) and goldfish (Carassius auratus). In their native range, some of the fish that northern snakeheads prey include perch (Perca fluviatilis), carp (Cyprinus carpio), bream (Abramis), and loach (Cobitis). Once seasonal water temperatures reach 10 degrees the northern snakeheads become fully active in their feeding habits. Northern snakeheads feed in schools, as many other snakehead species do, and prefer to hunt in low light scenarios. (Courtenay and Williams, 2004; Odenkirk, et al., 2013; Saylor, et al., 2012)",
  Impact:
    "Gambusia holbrooki predate on amphibian eggs; and predate and compete with tadpoles, resulting in injury or death to individuals. They may have a negative influence on some frog species' choice of breeding habitat. G. holbrooki have been shown to predate upon the eggs and tadpoles of the 'Critically Endangered (CR)' yellow-spotted tree frog (see Litoria castanea in IUCN Red List of Threatened Species); the 'Endangered (EN)' green and gold frog (see Litoria raniformis in IUCN Red List of Threatened Species); and the 'Vulnerable (VU)' golden bell frog (see Litoria aurea in IUCN Red List of Threatened Species) in Australia (NSW National Parks & Wildlife Service, 2004). Gambusia spp. have been implicated in the decline in the range and abundance of native fish species worldwide (Lloyd 1990) through predation and interference competition (McKay 1984; Howe 1995; Ivanstoff and Aarn 1999; Knight 1999). The species is purported to impact on macro-invertebrates such as rotifers, mayflies, beetles, dragonflies and molluscs (Anstis, 2002).",
  Control:
    "Preventative measures: Copp et al, (2005) Risk identification and assessment of non-native freshwater fishes presents a conceptual risk assessment approach for freshwater fish species that addresses the first two elements (hazard identification, hazard assessment) of the UK environmental risk strategy. The paper presents a few worked examples of assessments on species to facilitate discussion. The electronic Decision-support tools- Invasive-species identification tool kits that includes a freshwater and marine fish invasives scoring kit are made available on the Cefas (Centre for Environment, Fisheries & Aquaculture Science) page for free download (subject to Crown Copyright (2007-2008))./nChemical: Chemical control measures such as the application of Rotenone may be appropriate for small confined waterbodies, where impacts to non-target species can be minimised. Rotenone is indiscriminate, so non-target species ideally need to be removed prior to its application. Fish affected by Rotenone come to the surface to seek oxygen, so any remaining non-target species may be removed at this stage (Willis & Ling, 2000)./nPhysical: Physical control measures such as draining of a pond may be appropriate for small confined waterbodies, where impacts to non-target species can be minimised.",
  Kingdom: "Animalia",
  Phylum: "Chordata",
  Class: "Actinopterygii",
  Order: "Cyprinodontiformes",
  Family: "Poeciliidae",
  ImageURL:
    "https://firebasestorage.googleapis.com/v0/b/invasiveanimal-g4.appspot.com/o/Gambusia_Holbrooki1.jpg?alt=media&token=639b0027-4ad6-4b0a-91b5-be310c937d01"
};
